[default]

[default.backtest_settings]
timeframe = "1m"
start_date_iso = "2025-01-02T00:00:00Z"
end_date_iso = "2025-04-28T00:00:00Z"
initial_cash = 1000000
commission_percentage = 0.045
leverage = 10
slippage_percentage_per_side = 0.05
position_size_fraction = 0.05
active_strategy = "counter-trade"
symbol = "SUIUSDT"
backtest_modus = "both"

[default.app_settings]
debug_mode = false

[default.optimization_settings]
optimize_exit_signal_if_modus_both = true
target_metrics = ["Sharpe Ratio", "Sortino Ratio", "Return (Ann.) [%]"]
active_strategies = ["follow-the-flow", "counter-trade"]
symbols = [
    "ETHUSDT",
    "SOLUSDT",
    "SUIUSDT",
    "FARTCOINUSDT",
    "XRPUSDT",
    "TRUMPUSDT",
    "TAOUSDT",
    "LINKUSDT",
    "DOGEUSDT",
]
modus = ["buy", "sell", "both"]


[dev]

[dev.backtest_settings]
timeframe = "1m"
start_date_iso = "2025-01-01T00:00:00Z"
end_date_iso = "2025-01-10T00:00:00Z"
initial_cash = 1000000
commission_percentage = 0.045
leverage = 10
slippage_percentage_per_side = 0.05
position_size_fraction = 0.05
active_strategy = "follow-the-flow"
symbol = "BTCUSDT"
backtest_modus = "both"

[dev.app_settings]
debug_mode = false

[dev.optimization_settings]
optimize_exit_signal_if_modus_both = true
target_metrics = ["Sharpe Ratio", "Sortino Ratio"]
active_strategies = ["follow-the-flow", "counter-trade"]
symbols = ["BTCUSDT", "SUIUSDT"]
modus = ["buy", "both"]
