[default]
active_strategies = ["follow-the-flow", "counter-trade"]

[default.backtest_settings]
symbols = [
    "SOLUSDT",
    "FARTCOINUSDT",
    "MAGICUSDT",
    "XRPUSDT",
    "IMXUSDT",
    "SUIUSDT",
    "ENAUSDT",
]
timeframe = "1m"
start_date_iso = "2025-01-01T00:00:00Z"
end_date_iso = "2025-04-27T00:00:00Z"
initial_cash = 100000
commission_percentage = 0.045
leverage = 10
modus = ["buy", "sell", "both"]
slippage_percentage_per_side = 0.05
position_size_fraction = 0.05

[default.app_settings]
debug_mode = false

[default.optimization_settings]
optimize_exit_signal_if_modus_both = true
target_metrics = ["Sharpe Ratio", "Sortino Ratio", "Calmar Ratio", "Return [%]"]


[dev]
active_strategies = ["follow-the-flow", "counter-trade"]

[dev.backtest_settings]
symbols = ["SOLUSDT", "FARTCOINUSDT"]
timeframe = "1m"
start_date_iso = "2025-01-01T00:00:00Z"
end_date_iso = "2025-01-10T00:00:00Z"
initial_cash = 100000
commission_percentage = 0.045
leverage = 10
modus = ["buy", "both"]
slippage_percentage_per_side = 0.05
position_size_fraction = 0.05

[dev.app_settings]
debug_mode = false

[dev.optimization_settings]
optimize_exit_signal_if_modus_both = false
target_metrics = ["Sharpe Ratio", "Sortino Ratio"]
