[default]

[default.backtest_settings]
timeframe = "1m"
start_date_iso = "2025-01-01T00:00:00Z"
end_date_iso = "2025-04-27T00:00:00Z"
initial_cash = 1000000
commission_percentage = 0.045
leverage = 10
slippage_percentage_per_side = 0.05
position_size_fraction = 0.05
active_strategy = "follow-the-flow"     # Added single value
symbol = "SOLUSDT"                      # Added single value
backtest_modus = "both"                 # Added single value

[default.app_settings]
debug_mode = false

[default.optimization_settings]
optimize_exit_signal_if_modus_both = true
target_metrics = ["Sharpe Ratio", "Sortino Ratio", "Calmar Ratio", "Return [%]"]
active_strategies = ["follow-the-flow", "counter-trade"] # Moved list
symbols = [ # Moved list
    "SOLUSDT",
    "FARTCOINUSDT",
    "MAGICUSDT",
    "XRPUSDT",
    "IMXUSDT",
    "SUIUSDT",
    "ENAUSDT",
]
modus = ["buy", "sell", "both"] # Moved list


[dev]

[dev.backtest_settings]
timeframe = "1m"
start_date_iso = "2025-01-01T00:00:00Z"
end_date_iso = "2025-01-10T00:00:00Z"
initial_cash = 1000000
commission_percentage = 0.045
leverage = 10
slippage_percentage_per_side = 0.05
position_size_fraction = 0.05
active_strategy = "follow-the-flow"     # Added single value
symbol = "BTCUSDT"                      # Added single value
backtest_modus = "buy"                  # Added single value

[dev.app_settings]
debug_mode = false

[dev.optimization_settings]
optimize_exit_signal_if_modus_both = false
target_metrics = ["Sharpe Ratio", "Sortino Ratio"]
active_strategies = ["follow-the-flow", "counter-trade"] # Moved list
symbols = ["BTCUSDT", "FARTCOINUSDT"]                    # Moved list
modus = ["buy", "both"]                                  # Moved list
