[default.strategy_parameters]
average_liquidation_multiplier = 4.0
stop_loss_percentage = 1.0
take_profit_percentage = 2.0
exit_on_opposite_signal = false
modus = "both"  # "buy", "sell", or "both"
liquidation_aggregation_minutes = 5
average_lookback_period_days = 14

# Dev environment - can override default strategy parameters
[dev.strategy_parameters]
average_liquidation_multiplier = 4.0
stop_loss_percentage = 1.0
take_profit_percentage = 2.0
exit_on_opposite_signal = false
modus = "both"
liquidation_aggregation_minutes = 5
average_lookback_period_days = 14 # Consider a shorter period for dev testing if appropriate